import { Product } from '../types/game';

export const INITIAL_PRODUCTS: Record<string, Product> = {
  // Dairy Products
  Milk: {
    name: 'Milk',
    basePrice: 2.49,
    supplierPrice: 1.99,
    maxPrice: 3.99,
    tier: 1,
    isPerishable: true,
    expiryDays: 7,
    stock: 0,
    sellingPrice: 2.99,
    expiryDates: [],
  },
  Cheese: {
    name: 'Cheese',
    basePrice: 3.99,
    supplierPrice: 2.99,
    maxPrice: 5.99,
    tier: 2,
    isPerishable: true,
    expiryDays: 14,
    stock: 0,
    sellingPrice: 4.49,
    expiryDates: [],
  },
  Yogurt: {
    name: 'Yogurt',
    basePrice: 1.99,
    supplierPrice: 1.49,
    maxPrice: 2.99,
    tier: 1,
    isPerishable: true,
    expiryDays: 10,
    stock: 0,
    sellingPrice: 2.29,
    expiryDates: [],
  },

  // Bakery
  Bread: {
    name: 'Bread',
    basePrice: 1.99,
    supplierPrice: 1.49,
    maxPrice: 2.99,
    tier: 1,
    isPerishable: true,
    expiryDays: 5,
    stock: 0,
    sellingPrice: 2.39,
    expiryDates: [],
  },
  Croissants: {
    name: 'Croissants',
    basePrice: 2.99,
    supplierPrice: 2.29,
    maxPrice: 4.49,
    tier: 2,
    isPerishable: true,
    expiryDays: 3,
    stock: 0,
    sellingPrice: 3.49,
    expiryDates: [],
  },

  // Pantry Items
  Cereal: {
    name: 'Cereal',
    basePrice: 3.99,
    supplierPrice: 2.99,
    maxPrice: 5.99,
    tier: 1,
    stock: 0,
    sellingPrice: 4.79,
  },
  Pasta: {
    name: 'Pasta',
    basePrice: 1.49,
    supplierPrice: 0.99,
    maxPrice: 2.49,
    tier: 1,
    stock: 0,
    sellingPrice: 1.99,
  },
  Rice: {
    name: 'Rice',
    basePrice: 2.99,
    supplierPrice: 2.29,
    maxPrice: 4.49,
    tier: 1,
    stock: 0,
    sellingPrice: 3.49,
  },

  // Snacks
  Cookies: {
    name: 'Cookies',
    basePrice: 2.99,
    supplierPrice: 1.99,
    maxPrice: 4.99,
    tier: 1,
    stock: 0,
    sellingPrice: 3.59,
  },
  Chips: {
    name: 'Chips',
    basePrice: 2.49,
    supplierPrice: 1.79,
    maxPrice: 3.99,
    tier: 1,
    stock: 0,
    sellingPrice: 2.99,
  },
  Chocolate: {
    name: 'Chocolate',
    basePrice: 1.99,
    supplierPrice: 1.29,
    maxPrice: 3.49,
    tier: 1,
    stock: 0,
    sellingPrice: 2.49,
  },

  // Beverages
  Soda: {
    name: 'Soda',
    basePrice: 1.49,
    supplierPrice: 0.99,
    maxPrice: 2.49,
    tier: 1,
    stock: 0,
    sellingPrice: 1.99,
  },
  Coffee: {
    name: 'Coffee',
    basePrice: 4.99,
    supplierPrice: 3.99,
    maxPrice: 7.99,
    tier: 2,
    stock: 0,
    sellingPrice: 5.99,
  },

  // Fresh Produce
  Apples: {
    name: 'Apples',
    basePrice: 2.99,
    supplierPrice: 2.29,
    maxPrice: 4.49,
    tier: 1,
    isPerishable: true,
    expiryDays: 14,
    stock: 0,
    sellingPrice: 3.49,
    expiryDates: [],
  },
  Bananas: {
    name: 'Bananas',
    basePrice: 1.99,
    supplierPrice: 1.49,
    maxPrice: 2.99,
    tier: 1,
    isPerishable: true,
    expiryDays: 7,
    stock: 0,
    sellingPrice: 2.29,
    expiryDates: [],
  },
  Tomatoes: {
    name: 'Tomatoes',
    basePrice: 2.49,
    supplierPrice: 1.79,
    maxPrice: 3.99,
    tier: 1,
    isPerishable: true,
    expiryDays: 10,
    stock: 0,
    sellingPrice: 2.99,
    expiryDates: [],
  },
};